/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package music;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author KaitlinMoore
 */
public class MusicGUI extends javax.swing.JFrame {
    private Interface2 myLiked;
    private Interface1 myPop;
    private Interface1 myRap;
    
    /**
     * Creates new form MusicGUI
     */
    public MusicGUI() {
        initComponents();
        myLiked = new Liked();
        myPop = new Pop();
        myRap = new Rap();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Songlbl = new javax.swing.JLabel();
        Genrelbl = new javax.swing.JLabel();
        Songnamefld = new javax.swing.JTextField();
        SongGenrefld = new javax.swing.JTextField();
        Likesonglbl = new javax.swing.JLabel();
        Popsonglbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Likedsongfld = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        Popsongfld = new javax.swing.JTextArea();
        Rapsonglbl = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Rapsongfld = new javax.swing.JTextArea();
        Headinglbl = new javax.swing.JLabel();
        Addbtn = new javax.swing.JButton();
        Deletebtn = new javax.swing.JButton();
        Movebtn = new javax.swing.JButton();
        Displaybtn = new javax.swing.JButton();
        numbersongbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Songlbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Songlbl.setText("Song Name:");

        Genrelbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Genrelbl.setText("Song Genre:");

        Songnamefld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SongnamefldActionPerformed(evt);
            }
        });

        Likesonglbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Likesonglbl.setText("Liked Songs");

        Popsonglbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Popsonglbl.setText("Pop Songs");

        Likedsongfld.setColumns(20);
        Likedsongfld.setRows(5);
        jScrollPane1.setViewportView(Likedsongfld);

        Popsongfld.setColumns(20);
        Popsongfld.setRows(5);
        jScrollPane2.setViewportView(Popsongfld);

        Rapsonglbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Rapsonglbl.setText("Rap Songs");

        Rapsongfld.setColumns(20);
        Rapsongfld.setRows(5);
        jScrollPane3.setViewportView(Rapsongfld);

        Headinglbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Headinglbl.setText("Welcome to Apple Music Pop and Rap Playlist.");

        Addbtn.setText("Add ");
        Addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddbtnActionPerformed(evt);
            }
        });

        Deletebtn.setText("Delete");
        Deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletebtnActionPerformed(evt);
            }
        });

        Movebtn.setText("Move");
        Movebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MovebtnActionPerformed(evt);
            }
        });

        Displaybtn.setText("Display");
        Displaybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplaybtnActionPerformed(evt);
            }
        });

        numbersongbtn.setText("Number of Songs");
        numbersongbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numbersongbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Headinglbl, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Songlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Songnamefld, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Displaybtn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Movebtn))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Addbtn)
                                    .addGap(72, 72, 72)
                                    .addComponent(Deletebtn)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Genrelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SongGenrefld, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(numbersongbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Likesonglbl, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Popsonglbl, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Rapsonglbl, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Headinglbl, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Songnamefld, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Songlbl))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Likesonglbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Popsonglbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Rapsonglbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SongGenrefld, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Genrelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Addbtn)
                            .addComponent(Deletebtn))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Movebtn)
                            .addComponent(Displaybtn))
                        .addGap(18, 18, 18)
                        .addComponent(numbersongbtn)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SongnamefldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SongnamefldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SongnamefldActionPerformed

    private void AddbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddbtnActionPerformed
        // TODO add your handling code here:
        Music myM = new Music();
        
        String songName, songGenre;
        songName = Songnamefld.getText();
        songGenre = SongGenrefld.getText();
        myLiked.push(songName);
        Likedsongfld.append("A song called " + songName + " was added to liked songs\n");
        
    }//GEN-LAST:event_AddbtnActionPerformed

    private void DeletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletebtnActionPerformed
        // TODO add your handling code here:
        if(myLiked.isEmpty()){
            Likedsongfld.append("There are no songs to be removed!\n");
        }else{
           String songRemoved = (String) myLiked.pop();
           Likedsongfld.append("The song " + songRemoved + " was removed!\n");
        }
            
    }//GEN-LAST:event_DeletebtnActionPerformed

    private void numbersongbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numbersongbtnActionPerformed
        // TODO add your handling code here:
         Likedsongfld.append("There are " + myLiked.size() + " songs in the Liked songs playlist\n");
         Popsongfld.append("There are " + myPop.size() + " songs in the Pop songs playlist\n");
         Rapsongfld.append("There are " + myRap.size() + " songs in the Rap songs playlist\n");
    }//GEN-LAST:event_numbersongbtnActionPerformed

    private void DisplaybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplaybtnActionPerformed
        // TODO add your handling code here:
        Likedsongfld.append(myLiked.displayStack() + "\n");
        Popsongfld.append(myPop.displayQueue() + "\n");
        Rapsongfld.append(myRap.displayQueue() + "\n");
    }//GEN-LAST:event_DisplaybtnActionPerformed

    private void MovebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MovebtnActionPerformed
        // TODO add your handling code here:
        Music myM = new Music();
        
        myM.setsongName(Songnamefld.getText());
        myM.setsongGenre(SongGenrefld.getText());
        Songnamefld.setText("");
        SongGenrefld.setText("");
        
            if (myM.getsongGenre().equalsIgnoreCase("pop")){
                myPop.enqueue(myLiked.pop());
                Popsongfld.append(Songnamefld.getText() + ", was successfully added to the Pop playlist\n");
           
            }else if (myM.getsongGenre().equalsIgnoreCase("rap")){
                myRap.enqueue(myLiked.pop());
                Rapsongfld.append(myM.getsongGenre() + ", was successfully added to the Rap playlist\n");
                
            }else{
               Likedsongfld.append(" Invalid input, please enter Pop or Rap\n");
            }
    }//GEN-LAST:event_MovebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MusicGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MusicGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MusicGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MusicGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MusicGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addbtn;
    private javax.swing.JButton Deletebtn;
    private javax.swing.JButton Displaybtn;
    private javax.swing.JLabel Genrelbl;
    private javax.swing.JLabel Headinglbl;
    private javax.swing.JTextArea Likedsongfld;
    private javax.swing.JLabel Likesonglbl;
    private javax.swing.JButton Movebtn;
    private javax.swing.JTextArea Popsongfld;
    private javax.swing.JLabel Popsonglbl;
    private javax.swing.JTextArea Rapsongfld;
    private javax.swing.JLabel Rapsonglbl;
    private javax.swing.JTextField SongGenrefld;
    private javax.swing.JLabel Songlbl;
    private javax.swing.JTextField Songnamefld;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton numbersongbtn;
    // End of variables declaration//GEN-END:variables
}